using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace edtech_platform_api.Migrations
{
    public partial class AddPasswordResetTokenEntity : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "PasswordResetTokens" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "UserId" integer NOT NULL,
                    "TokenHash" character varying(128) NOT NULL,
                    "ExpiresAt" timestamp with time zone NOT NULL,
                    "IsUsed" boolean NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
                    CONSTRAINT "PK_PasswordResetTokens" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_PasswordResetTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql("""CREATE UNIQUE INDEX IF NOT EXISTS "IX_PasswordResetTokens_TokenHash" ON "PasswordResetTokens" ("TokenHash");""");
            migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_PasswordResetTokens_UserId_IsUsed_ExpiresAt" ON "PasswordResetTokens" ("UserId", "IsUsed", "ExpiresAt");""");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "PasswordResetTokens";""");
        }
    }
}
